name: Move opened issues into the No Status column in the Writers project
on:
  issues:
    types:
      - opened
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Writers
          column: No Status
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}

